# Libraries in Python

# NUMPY

![Class Image](images/class19.png)

![Class Image](images/class20.png)

![Class Image](images/class21.png)

In [1]:
import numpy as np

In [5]:
l1 = [10, 20, 30, 40]

In [6]:
n1 = np.array(l1)
n1

array([10, 20, 30, 40])

In [9]:
n2 = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [10]:
type(n2)

numpy.ndarray

![Class Image](images/class22.png)

In [13]:
n1 = np.zeros((1, 2)) # 1 row, 2 columns
n1

array([[0., 0.]])

In [16]:
n2 = np.zeros((3, 5)) # 5 rows, 5 columns
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

![Class Image](images/class23.png)

In [17]:
n4 = np.full((2, 3), 55)
n4

array([[55, 55, 55],
       [55, 55, 55]])

![Class Image](images/class24.png)

In [ ]:
n5 = np.arange(1, 11) # strats form 1, finishes at 10
n5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
n6 = np.arange(1, 11, 2) , # step of 2
n6

array([1, 3, 5, 7, 9])

![Class Image](images/class25.png)

In [22]:
n7 = np.random.randint(100, 200, 10) # return 10 random values btw 100 and 200
n7

array([142, 109, 143, 110, 140, 124, 184, 121, 113, 195])

![Class Image](images/class26.png)

In [24]:
n8 = np.array([[1, 2, 3, 4], [4, 3, 2, 1]])
n8

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [26]:
n8.shape

(2, 4)

In [27]:
n8.shape = (4, 2)
n8

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [28]:
n8.shape = (8, 1)
n8

array([[1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1]])

![Class Image](images/class27.png)

In [29]:
n9 = np.array([1, 2, 3])
n10 = np.array([4, 5, 6])

In [31]:
np.vstack((n9, n10))

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.hstack((n9, n10))

array([1, 2, 3, 4, 5, 6])

In [33]:
np.column_stack((n9, n10))

array([[1, 4],
       [2, 5],
       [3, 6]])

![Class Image](images/numpy1.png)

In [34]:
n11 = np.array([10, 20, 30, 40, 50, 60])
n12 = np.array([50, 60, 70, 80, 90])

In [36]:
np.intersect1d(n11, n12)

array([50, 60])

In [37]:
np.setdiff1d(n11, n12)

array([10, 20, 30, 40])

In [38]:
np.setdiff1d(n12, n11)

array([70, 80, 90])

![Numpy Image](images/numpy2.png)

In [39]:
n13 = np.array([10, 20])
n14 = np.array([30, 40])

In [41]:
np.sum([n13, n14])

100

In [42]:
np.sum([n13, n14], axis = 0)

array([40, 60])

In [43]:
np.sum([n13, n14], axis = 1)

array([30, 70])

![Numpy Image](images/numpy3.png)

In [58]:
n15 = np.array([10, 20, 30])
n15 + 5

array([15, 25, 35])

In [59]:
n15 - 5

array([ 5, 15, 25])

In [60]:
n15 * 10

array([100, 200, 300])

In [61]:
n15 / 5

array([2., 4., 6.])

![Numpy Image](images/numpy4.png)

In [62]:
n16 = np.random.randint(1, 50, 10)
n16

array([36, 15, 41, 46, 27,  9, 23, 30, 38, 12])

In [63]:
np.mean(n16)

27.7

In [64]:
np.median(n16)

28.5

In [65]:
np.std(n16)

12.133012816279392

![Numpy Image](images/numpy5.png)

## Excercises:

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code to create a numpy array from it?

In [6]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# 1D array
np_baseball_1d = np.array(baseball)
print("1D array:", np_baseball_1d)
print("Shape:", np_baseball_1d.shape)
print("First element:", np_baseball_1d[0])

# 2D array
np_baseball_2d = np.array([baseball])
print("\n2D array:", np_baseball_2d)
print("Shape:", np_baseball_2d.shape)
print("First element:", np_baseball_2d[0, 0])  # Need two indices

1D array: [180 215 210 210 188 176 209 200]
Shape: (8,)
First element: 180

2D array: [[180 215 210 210 188 176 209 200]]
Shape: (1, 8)
First element: 180


You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

In [8]:
height_in = [74, 74, 72, 75, 75, 73, 71, 79,78]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254
print(np_height_m)

[74 74 72 75 75 73 71 79 78]
[1.8796 1.8796 1.8288 1.905  1.905  1.8542 1.8034 2.0066 1.9812]


Subsetting (using the square bracket notation on lists or arrays) works exactly the same with both lists and arrays.

This exercise already has two lists, height_in and weight_lb, loaded in the background for you. These contain the height and weight of the MLB players as regular lists. It also has two numpy array lists, np_weight_lb and np_height_in prepared for you.

In [ ]:
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180,
             188, 180, 185, 160, 180, 185, 189, 185, 219, 230]
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73,
                74, 74, 69, 70, 73, 75, 78, 79]

np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 10
print(np_weight_lb[9])

# Print out sub-array of np_height_in: index 10 up to and including index 16
print(np_height_in[9:16])

180
[71 73 73 74 74 69 70]


let's try to create a 2D numpy array from a small list of lists.
In this exercise, baseball is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

In [3]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


Baseball data in 2D form

You realize that it makes more sense to restructure all this information in a 2D numpy array.

You have a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. 

Store the data as a 2D array to unlock numpy's extra functionality.

In [5]:
baseball = [[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], [76, 231], [71, 180], [73, 188], [73, 180], 
            [74, 185], [74, 160], [69, 180], [70, 185], [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195], [72, 180]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(24, 2)


Subsetting 2D NumPy Arrays

The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.

In [6]:
# Print out the 20th row of np_baseball
print(np_baseball[19, :])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]
print("Entire second column (weights):", np_weight_lb)

# Print out height of 14th player
print(np_baseball[13, 0])

[ 79 230]
Entire second column (weights): [180 215 210 210 188 176 209 200 231 180 188 180 185 160 180 185 189 185
 219 230 205 230 195 180]
74


2D Arithmetic

2D numpy arrays can perform calculations element by element, like numpy arrays.

np_baseball is coded for you; it's again a 2D numpy array with 3 columns representing height (in inches), weight (in pounds) and age (in years). baseball is available as a regular list of lists and updated is available as 2D numpy array.

You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.
You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
Multiply np_baseball with conversion and print out the result.

In [7]:
baseball = [[74.0, 180.0, 22.99], [74.0, 215.0, 34.69], [72.0, 210.0, 30.78], [72.0, 210.0, 35.43], [73.0, 188.0, 35.71], 
            [69.0, 176.0, 29.39], [69.0, 209.0, 30.77], [71.0, 200.0, 35.07], [76.0, 231.0, 30.19], [71.0, 180.0, 27.05], 
            [73.0, 188.0, 23.88], [73.0, 180.0, 26.96], [74.0, 185.0, 23.29], [74.0, 160.0, 26.11], [69.0, 180.0, 27.55]]

updated = np.array([
    [1.0, 2.0, 0.1], [0.0, -2.0, 0.2], [1.0, 0.0, -0.1],
    [0.0, 3.0, 0.3], [1.0, 1.0, 0.0], [-1.0, -1.0, -0.2],
    [0.0, 2.0, 0.1], [1.0, 1.0, 0.2], [0.0, 0.0, 0.0],
    [-1.0, -2.0, -0.3], [0.0, 1.0, 0.1], [1.0, 0.0, 0.2],
    [0.0, -1.0, -0.1], [-1.0, -2.0, -0.2], [0.0, 0.0, 0.0]
])

np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 75.   182.    23.09]
 [ 74.   213.    34.89]
 [ 73.   210.    30.68]
 [ 72.   213.    35.73]
 [ 74.   189.    35.71]
 [ 68.   175.    29.19]
 [ 69.   211.    30.87]
 [ 72.   201.    35.27]
 [ 76.   231.    30.19]
 [ 70.   178.    26.75]
 [ 73.   189.    23.98]
 [ 74.   180.    27.16]
 [ 74.   184.    23.19]
 [ 73.   158.    25.91]
 [ 69.   180.    27.55]]
[[  1.8796    81.64656   22.99    ]
 [  1.8796    97.52228   34.69    ]
 [  1.8288    95.25432   30.78    ]
 [  1.8288    95.25432   35.43    ]
 [  1.8542    85.275296  35.71    ]
 [  1.7526    79.832192  29.39    ]
 [  1.7526    94.800728  30.77    ]
 [  1.8034    90.7184    35.07    ]
 [  1.9304   104.779752  30.19    ]
 [  1.8034    81.64656   27.05    ]
 [  1.8542    85.275296  23.88    ]
 [  1.8542    81.64656   26.96    ]
 [  1.8796    83.91452   23.29    ]
 [  1.8796    72.57472   26.11    ]
 [  1.7526    81.64656   27.55    ]]


In [10]:
# Print average
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:, 0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:, 0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr =  np.corrcoef(np_baseball[:, 0], np_baseball[:, 1])
print("Correlation: " + str(corr))

Average: 72.26666666666667
Median: 73.0
Standard Deviation: 2.048305532764962
Correlation: [[1.         0.20330919]
 [0.20330919 1.        ]]


In [9]:
# Print out the mean of np_height_in
mean = np.mean(np_height_in)
print(f"The mean height is {mean}")

# Print out the median of np_height_in
median = np.median(np_height_in)
print(f"The median height is {median}")

The mean height is 74.55555555555556
The median height is 74.0
